apps/audioplayers/wavplay.cpp
services/bt_app/app_a2dp.cpp

Reading through the source I found a couple spots where the work "palyback" was used when "playback" seemed to be the intention. This PR corrects those misspellings. 
I ran through the build process and it succeed with a binary that's the same size as the original. I haven't yet deployed it to hardware. Would the maintainers recommend deploying to actual Pinebuds before submitting a PR? I'm happy to test it out if the firmware is considered safe to use. Thanks!

Fixed a typo where 'playback' was sometimes spelled 'palyback'

---

.gitignore
README.md
backup.sh

I put together a script called `backup.sh` that handles creating firmware backups with `bestool`. The script is based on `./download.sh` and is still pretty similar to it. The script places firmware backups in `firmware-backups/` with names like `firmware-1672882716-0.bin.bkp`, where `1672882716` is the UNIX time at the start of the script and `-0` indicates the firmware is from the right bud. A `-1` indicates it's from the left.

Add backup script

---

.github/dependabot.yml
.gitignore

This commit adds support for Dependabot, which will automatically make PRs on a weekly basis (if necessary) for GitHub Actions and the Dockerfile.
As per my note in #7, this PR is the end result of splitting that PR into multiple PRs for tracking purposes.

Add support for Dependabot

---

.github/workflows/build-and-push-to-registry.yml
.gitignore

This commit adds support for a container build workflow, that, upon pushes to the repo, but *not* pull requests, builds a container image at one at a time, and pushes to GitHub Registry.
As per my note in #7, this PR is the end result of splitting that PR into multiple PRs for tracking purposes.

Add support for GH Actions container build workflow

---

Dockerfile
docker-compose.yml

- Use Debian Bullseye as `base` image.
- Use proper `LABEL` for authors/maintainers.
- Multi-stage builds.
- Download Rust via rustup.
- Combine RUN commands to reduce layers.

Refactor Dockerfile - see description

---

.devcontainer/devcontainer.json
.gitignore

This commit adds a .devcontainer directory, with the Dockerfile in the configuration told to use the Dockerfile in the parent directory.
Using Development Containers means the environment is reproducible on developer machines,
and reduces the barrier to entry for development. It also allows GitHub Codespaces to be used.
Signed-off-by: Dom Rodriguez <shymega@shymega.org.uk>

Initial commit for the Development Container config

---

README.md

- Baudrate is 2M baud (not 200,000)
- "pine buds" to "PineBuds" to match the product's webpage
- One spelling change

A couple README typo fixes

---

backup.sh
build.sh
clear.sh
download.sh
uart_log.sh

Apply some suggestions from `shellcheck`. It also suggests replacing the `ls -l` with `find`, which I agree with, but that changes the order the files get outputted in. This means that the left/right is even less reliable.

Apply changes suggested by shellcheck

---

backup.sh
build.sh
clear.sh
convert.sh
download.sh
start_dev.sh
uart_log.sh

This resolves build errors in systems like NixOS, where `/bin/bash` doesn't exist.

refactor(scripts): Use `#!/usr/bin/env` as part of shebang

---

Makefile
scripts/build.mk

This improves portability, especially on systems like NixOS, where `/bin/pwd` and `/usr/bin/printf` do not exist.

fix(makefile): Use shell-builtins in Makefile

---

README.md
config/_default_cfg_src_/app_status_ind.c
config/common.mk

Maybe this is just me, feel free to close this if it is, but I really dislike the flashing of the blue light when the buds are connected. I think it's completely unnecessary and even a bit confusing.
This seemed to work if I completely removed the code in the `APP_STATUS_INDICATION_CONNECTED` case, but that seems to me like it would just keep the LED in the state it is in before it connected. Let me know if that assumption is wrong.

Don't flash blue LED when connected to bluetooth

---

docker-compose.yml

This changes the `docker-compose.yml` file to use the Pine64 OpenPineBuds repository's container image for the development environment, but the user has the option to build from scratch.

compose: Use repository's container image for dev env

---

.github/workflows/build-and-push-to-registry.yml

This PR changes the 'build-and-push-to-registry' workflow to only run on the Pine64 repository, which prevents image pushing errors occurring.
By doing this, we ensure the container images only come from the Pine64 OpenPineBuds repository.

Fix container builds on forks

---

.github/workflows/build-and-push-to-registry.yml

This limits the container workflow from building on non-`main` branches.
Otherwise, we have unstable and WIP container images available.

Limit container workflow runs to `main` branch *only*

---

apps/anc/src/app_anc.c
apps/main/key_handler.cpp
services/app_ibrt/src/app_ibrt_keyboard.cpp

Switching ANC on or off from master bud has always worked since we could just straight up enable it and no command had to be sent.
When switching from slave bud we had to send the command to enable or disable it via app_anc_key. Issue is the handling of this request is from app_anc_cmd_receive_process which is not called without APP_ANC being defined.
This commit cleans up the way ANC is enabled and also fixes slave bud ANC switching by implementing the actual code path :)
Please note that the ANC testing branch should be rebased on top of main with this commit added.
I did my testing with main merged with anc_testing branch thus why the key_handling.cpp file :)

anc: Fix enable/disable from slave bud

---

uart_log.sh

Pick the serial device by ID, allowing us to safely predict the paths to find the left and right bud at
Also improve the script so it asks which bud we'd like to debug
Specify necessary minicom options, so it opens even if the default configuration is invalid

Update uart_log.sh for easier debugging

---

config/open_source/target.mk
services/bt_app/app_bt_stream.cpp

- Permits LDAC to be enabled independenly of LHDC (they don't depend on each other and aren't related, other than they both go through the `BTIF_AVDTP_CODEC_TYPE_NON_A2DP` path and need a buffer bigger than 102400)
- Enables LDAC in the open_source target
- Fixes a bug/oversight in `bt_sbc_player` which caused system frequencies above 52M to be ignored (LDAC seems to target a 96k sample rate by default and thus needs 104M, as specified [here](https://github.com/pine64/OpenPineBuds/blob/main/services/bt_app/app_bt_stream.cpp#L3850) and [here](https://github.com/pine64/OpenPineBuds/blob/main/services/bt_app/app_bt_stream.cpp#L3862).)
I'm not sure if the [line](https://github.com/pine64/OpenPineBuds/blob/main/services/bt_app/app_bt_stream.cpp#L3869) was originally added for debug purposes …

Enable LDAC in the build

---

Dockerfile
uart_log.sh

Currently the docker image doesn't include minicom (or sudo), leaving the user to use the script outside the dev container.
This PR:
- Adds minicom and sudo to the docker image
- Switches the shebang line of `uart_log.sh` to bash. The -n option to read requires bash, and without this fix the script works inside the container (assuming you applied Dockerfile changes), but always selects the left bud

Functional UART logging both inside and outside dev container

---

apps/main/key_handler.cpp

Hello,
I read trough few files and this one stood out mostly due to redundancy of the if checks.
The if checks would be useful if we did something different for single tap in single or tws mode but we currently use single tap in both modes for pause or play. So no need for the checks.
In quad tap we dont have any action for right or left earbud (I think when we add passtrough mode this could be a good place to enable it) so for now we can simply remove the checks :)
All in all its just a tiny cleanup of the file :)
(This has been tested and all works as expected on my pinebuds)

main: key_handler.cpp: Remove redundant checks

---

docker-compose.yml

Removes the version attribute from docker-compose.yml to prevent the warning. Apparently this attribute did not have any effect, so there shouldn't be any problems from removing it.

Fix the attribute `version` is obsolete warning
